"""Canonical prompt rendering — build the prompt the SERVER will actually use.

Training scores tokens on a prompt built in-process with the HF chat template;
serving conditions on a prompt built by the inference server. For gpt-oss those
two are NOT the same string, so a trainer optimises a slightly different context
than the one its checkpoint is later served under, and an on-policy objective
teacher-forces rollouts onto a context they were not sampled from.

Two measured causes (gpt-oss-20b, vLLM 0.22.1):

  1. The tools sentence. The gpt-oss chat template appends
     "Calls to these tools must go to the commentary channel: 'functions'."
     under `{% if tools is defined %}` — and `transformers` ALWAYS passes
     `tools=` to the template (as None when there are none), so the guard is
     always true and the line is always rendered. vLLM builds its prompt with
     `openai_harmony` instead, which emits that line only when function tools
     really exist. Net: every HF-rendered gpt-oss prompt carries 14 tokens the
     server never sends. Measured effect on the model's own distribution: 0.0014
     nats/token, 98.1% top-1 agreement — small, but systematic and free to remove.

  2. The date. Both sides stamp "Current date: <today>", but vLLM re-stamps it
     PER REQUEST from `datetime.now()` unless VLLM_SYSTEM_START_DATE is set (its
     source calls this out as non-determinism), and the HF template's
     `strftime_now` is not overridable at all. A run that crosses midnight — or a
     checkpoint served the day after it was trained — silently shifts one token.
     config.SYSTEM_START_DATE pins both sides to one date for the whole run;
     vllm_server exports it to the server process.

`serving_prompt_ids` renders through `openai_harmony` (the very library vLLM
uses, installed as its dependency) so the trainer's prompt is byte-identical to
the served one, and falls back to the chat template when harmony is unavailable
or the model is not gpt-oss.

`continuation_prompt_ids` extends that to the case the probing path needs: a
prompt that stops MID-message, so the model continues an assistant turn already
in progress rather than starting a new one. That cannot be expressed as a chat
request at all on gpt-oss — see its docstring — so callers that need it must
drive `/v1/completions` with the ids it returns, not `/v1/chat/completions`.
"""
from __future__ import annotations

from typing import Optional

from . import config
from .utils import logger

_harmony_encoding = None
_harmony_unavailable = False

# Harmony control tokens. An assistant message is
# `<|start|>assistant<|channel|>{channel}<|message|>{body}<|end|>`, and the
# channel header is GENERATED by the model — `serving_prompt_ids` stops right
# before it (see sft.dataset._render, which relies on the same split).
_CHANNEL, _MESSAGE = "<|channel|>", "<|message|>"

# The channel a partial chain-of-thought belongs on. gpt-oss reasons in
# `analysis` and only opens `final` once it starts answering, which is why
# inference_script reads the trace back off `message.reasoning_content`. A
# truncated reasoning trace resumed on any other channel is off-distribution.
ANALYSIS_CHANNEL = "analysis"

# What terminates generation. gpt-oss keeps <|return|>/<|call|>/<|endoftext|> in
# generation_config.json (see optimization_script.save_merged_model), but NOT
# <|end|> — which is the token that closes a single message. A continuation that
# must stop at the end of the message it is extending, instead of running on into
# the next turn, has to ask for <|end|> explicitly.
_HARMONY_STOP_TOKENS = ("<|return|>", "<|end|>", "<|call|>", "<|endoftext|>")

# The subset of the above that means "wrap this turn up" rather than "something
# else happened". Used by the token-budget penalty (config.LENGTH_PENALTY), which
# maximises the probability of ending the turn at over-budget positions: <|end|>
# closes the message the model is currently writing (in gpt-oss's analysis channel
# that is how a chain-of-thought concludes before the final channel opens), and
# <|return|> ends the assistant turn outright. <|call|> (a tool invocation) and
# <|endoftext|> (a base-model artifact) are NOT wrap-up moves — rewarding them
# would teach the model to emit a tool call or a raw EOS to escape the budget.
_HARMONY_TURN_END_TOKENS = ("<|end|>", "<|return|>")


def _encoding():
    """The harmony encoding vLLM renders with, or None if it isn't importable."""
    global _harmony_encoding, _harmony_unavailable
    if _harmony_encoding is None and not _harmony_unavailable:
        try:
            from openai_harmony import HarmonyEncodingName, load_harmony_encoding

            _harmony_encoding = load_harmony_encoding(HarmonyEncodingName.HARMONY_GPT_OSS)
        except Exception as exc:  # not installed, or a version we can't drive
            _harmony_unavailable = True
            logger.warning(
                "openai_harmony is unavailable (%s); prompts fall back to the HF chat "
                "template, which renders 14 tokens of tool boilerplate the vLLM server "
                "does not send. Harmless but systematic — see pipeline/prompts.py.", exc,
            )
    return _harmony_encoding


def speaks_harmony(model_path: str) -> bool:
    """True if `model_path` names a gpt-oss model (the harmony-format family)."""
    from .utils import model_family

    return (model_family(model_path) or "").startswith("gpt-oss")


def serving_prompt_ids(
    system: str,
    user: str,
    tokenizer,
    *,
    model_path: Optional[str] = None,
) -> list[int]:
    """Token ids for [system, user] plus the assistant-turn opening.

    This is what the model is conditioned on at inference: for gpt-oss the
    sequence ends at `<|start|>assistant`, and whatever follows is generated
    (channel header included — see sft.dataset._render).

    Mirrors vLLM's `_make_request_with_harmony` + `parse_chat_inputs_to_harmony_messages`:
    harmony's own SYSTEM message (identity / knowledge cutoff / date / valid
    channels) is GENERATED, and an OpenAI-style `system` message is appended after
    it as a second, verbatim system-role message — NOT as developer instructions,
    and without the "# Instructions" header the chat template adds. Verified
    against the engine: a request echoing `prompt_token_ids` comes back with
    `…# Valid channels: …<|end|><|start|>system<|message|>{system}<|end|>…`.

    Falls back to the HF chat template for non-gpt-oss models or when
    openai_harmony is unavailable.
    """
    model_path = model_path or config.HF_MODEL_PATH
    enc = _encoding() if speaks_harmony(model_path) else None
    if enc is None:
        return _chat_template_ids(system, user, tokenizer)

    from openai_harmony import Conversation, Message, Role, SystemContent

    sys_content = SystemContent.new().with_conversation_start_date(config.SYSTEM_START_DATE)
    conversation = Conversation.from_messages([
        Message.from_role_and_content(Role.SYSTEM, sys_content),
        Message.from_role_and_content(Role.SYSTEM, system),
        Message.from_role_and_content(Role.USER, user),
    ])
    return list(enc.render_conversation_for_completion(conversation, Role.ASSISTANT))


def continuation_prompt_ids(
    system: str,
    user: str,
    assistant_prefix: str,
    tokenizer,
    *,
    model_path: Optional[str] = None,
    channel: str = ANALYSIS_CHANNEL,
) -> list[int]:
    """Token ids for [system, user] plus an assistant turn left OPEN mid-message.

    The result ends inside the assistant message, at the last character of
    `assistant_prefix`, so the next token is a continuation of that sentence:

        …<|start|>assistant<|channel|>analysis<|message|>{assistant_prefix}
                                                                          ^ next token

    This is NOT what a [system, user, assistant] chat request produces, on either
    side of the wire, and the difference is the whole reason this function exists:

      • `apply_chat_template(..., continue_final_message=True)` closes over the
        gpt-oss template's no-`thinking` branch, which renders a bare
        `<|start|>assistant<|message|>` — no channel. That sequence never occurs
        in harmony (the system message it sits under literally says "Channel must
        be included for every message"), and the model degenerates there.
        sft.dataset documents the same trap on the training side.
      • vLLM does not render gpt-oss with the chat template at all — it builds the
        prompt with `openai_harmony`, so `continue_final_message` never reaches a
        renderer that could honour it. An assistant message in the request is
        emitted CLOSED and a fresh turn is opened after it:
        `…<|message|>{assistant_prefix}<|end|><|start|>assistant`. The engine then
        samples `<|channel|>` and restarts its reasoning, having read the prefix
        as a completed turn rather than one to extend.

    So a mid-message continuation can only be driven through `/v1/completions`
    with these ids passed as `prompt`, which also makes the trainer's and the
    server's conditioning identical by construction rather than by agreement
    between two renderers.

    Non-gpt-oss models keep the chat template's own continuation rendering, which
    is well-defined for the ordinary `<|im_start|>`-style templates.
    """
    model_path = model_path or config.HF_MODEL_PATH
    if not speaks_harmony(model_path):
        return _chat_template_continuation_ids(system, user, assistant_prefix, tokenizer)

    # serving_prompt_ids stops at `<|start|>assistant`; the channel header and the
    # partial body are exactly what the model would have generated from there.
    ids = serving_prompt_ids(system, user, tokenizer, model_path=model_path)
    header = tokenizer.encode(f"{_CHANNEL}{channel}{_MESSAGE}", add_special_tokens=False)
    return list(ids) + list(header) + _encode_body(assistant_prefix, tokenizer)


def _encode_body(text: str, tokenizer) -> list[int]:
    """Encode message-body text so control tokens in it stay literal text.

    `add_special_tokens=False` only suppresses the AUTOMATIC bos/eos; a fast
    tokenizer still matches added special tokens appearing IN the string, so
    "…<|end|>…" encodes to control token 200007 rather than to its characters
    (verified on the gpt-oss vocab). The body here is model- and teacher-generated
    text — a truncated reasoning trace and a hint — so a stray `<|end|>` or
    `<|start|>` would close the analysis message and turn what is supposed to be
    one open assistant turn into a multi-turn conversation, silently, with the
    teacher and student then scored on a malformed context.

    harmony renders message bodies as literal text, so encoding them as literal
    text is also what keeps the two halves of this function agreeing.
    `split_special_tokens` needs a recent tokenizers; older ones fall back to the
    plain encode, which is the status quo rather than a regression.
    """
    try:
        return list(tokenizer.encode(
            text, add_special_tokens=False, split_special_tokens=True
        ))
    except TypeError:
        return list(tokenizer.encode(text, add_special_tokens=False))


def turn_end_token_ids(tokenizer, *, model_path: Optional[str] = None) -> list[int]:
    """Ids of the tokens that wrap up an assistant turn (see _HARMONY_TURN_END_TOKENS).

    The target set for the token-budget penalty. Falls back to the tokenizer's
    eos_token_id for non-harmony models, and returns [] if even that is missing —
    callers treat an empty set as "no length signal available here" and skip the
    term rather than training toward an arbitrary id.
    """
    if not speaks_harmony(model_path or config.HF_MODEL_PATH):
        eos = getattr(tokenizer, "eos_token_id", None)
        return [int(eos)] if eos is not None else []
    unk = getattr(tokenizer, "unk_token_id", None)
    ids = []
    for token in _HARMONY_TURN_END_TOKENS:
        tid = tokenizer.convert_tokens_to_ids(token)
        if tid is not None and tid != unk:
            ids.append(int(tid))
    return ids


def harmony_stop_token_ids(tokenizer, *, model_path: Optional[str] = None) -> list[int]:
    """Token ids that should end a single-message continuation, or [] if not gpt-oss.

    Includes `<|end|>` alongside the generation_config stop tokens, so a
    continuation of one assistant message stops when that message closes instead
    of running on into the next turn (see _HARMONY_STOP_TOKENS). Unknown tokens
    are dropped rather than raising: a tokenizer without them is not gpt-oss, and
    the caller's own eos handling is the right fallback.
    """
    if not speaks_harmony(model_path or config.HF_MODEL_PATH):
        return []
    unk = getattr(tokenizer, "unk_token_id", None)
    ids = []
    for token in _HARMONY_STOP_TOKENS:
        tid = tokenizer.convert_tokens_to_ids(token)
        if tid is not None and tid != unk:
            ids.append(int(tid))
    return ids


def _chat_template_ids(system: str, user: str, tokenizer) -> list[int]:
    """Fallback: the tokenizer's own chat template, opening an assistant turn."""
    ids = tokenizer.apply_chat_template(
        [{"role": "system", "content": system}, {"role": "user", "content": user}],
        tokenize=True,
        add_generation_prompt=True,
        return_tensors=None,
    )
    if hasattr(ids, "input_ids"):  # newer transformers returns a BatchEncoding
        ids = ids["input_ids"]
    return list(ids)


def _chat_template_continuation_ids(
    system: str, user: str, assistant_prefix: str, tokenizer
) -> list[int]:
    """Fallback for non-gpt-oss models: the template's own `continue_final_message`.

    Ordinary instruct templates render a final assistant message as an open
    prefix under this flag, which is precisely what we want. Older transformers
    that don't accept the kwarg fall back to opening a generation prompt and
    appending the prefix text — the same shape, built by hand.
    """
    messages = [
        {"role": "system", "content": system},
        {"role": "user", "content": user},
        {"role": "assistant", "content": assistant_prefix},
    ]
    try:
        ids = tokenizer.apply_chat_template(
            messages,
            tokenize=True,
            add_generation_prompt=False,
            continue_final_message=True,
            return_tensors=None,
        )
    except TypeError:  # transformers too old for continue_final_message
        return _chat_template_ids(system, user, tokenizer) + _encode_body(
            assistant_prefix, tokenizer
        )
    if hasattr(ids, "input_ids"):
        ids = ids["input_ids"]
    return list(ids)
